// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp3.DataBase;

#nullable disable

namespace WpfApp3.Migrations
{
    [DbContext(typeof(MagazinContextDb))]
    [Migration("20240525235720_DeleteCategory")]
    partial class DeleteCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WpfApp3.Models.BonCasa", b =>
                {
                    b.Property<int>("BonCasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BonCasaId"));

                    b.Property<int>("CasierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEliberarii")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SumaIncasata")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("BonCasaId");

                    b.HasIndex("CasierId");

                    b.ToTable("BonCasa");
                });

            modelBuilder.Entity("WpfApp3.Models.BonCasaDetalii", b =>
                {
                    b.Property<int>("BonCasaDetaliuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BonCasaDetaliuId"));

                    b.Property<int>("BonCasaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdusId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BonCasaDetaliuId");

                    b.HasIndex("BonCasaId");

                    b.HasIndex("ProdusId");

                    b.ToTable("BonCasaDetalii");
                });

            modelBuilder.Entity("WpfApp3.Models.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieId");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("WpfApp3.Models.Stoc", b =>
                {
                    b.Property<int>("ProducatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProducatorId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaraDeOrigine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProducatorId");

                    b.ToTable("Stoc");
                });

            modelBuilder.Entity("WpfApp3.Models.Produs", b =>
                {
                    b.Property<int>("ProdusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdusId"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("CodDeBare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretNormal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PretRedus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProducatorId")
                        .HasColumnType("int");

                    b.HasKey("ProdusId");

                    b.HasIndex("CategorieId");

                    b.HasIndex("ProducatorId");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("WpfApp3.Models.Stoc", b =>
                {
                    b.Property<int>("StocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StocId"));

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataAprovizionarii")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpirarii")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("PretAchizitie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PretVanzare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdusId")
                        .HasColumnType("int");

                    b.Property<string>("UnitateDeMasura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StocId");

                    b.HasIndex("ProdusId");

                    b.ToTable("Stoc");
                });

            modelBuilder.Entity("WpfApp3.Models.Utilizator", b =>
                {
                    b.Property<int>("UtilizatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilizatorId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipUtilizator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UtilizatorId");

                    b.ToTable("Utilizator");
                });

            modelBuilder.Entity("WpfApp3.Models.Vanzare", b =>
                {
                    b.Property<int>("VanzareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VanzareId"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Suma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UtilizatorId")
                        .HasColumnType("int");

                    b.HasKey("VanzareId");

                    b.HasIndex("UtilizatorId");

                    b.ToTable("Vanzare");
                });

            modelBuilder.Entity("WpfApp3.Models.BonCasa", b =>
                {
                    b.HasOne("WpfApp3.Models.Utilizator", "Casier")
                        .WithMany()
                        .HasForeignKey("CasierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casier");
                });

            modelBuilder.Entity("WpfApp3.Models.BonCasaDetalii", b =>
                {
                    b.HasOne("WpfApp3.Models.BonCasa", "BonCasa")
                        .WithMany("Detalii")
                        .HasForeignKey("BonCasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WpfApp3.Models.Produs", "Produs")
                        .WithMany()
                        .HasForeignKey("ProdusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonCasa");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("WpfApp3.Models.Produs", b =>
                {
                    b.HasOne("WpfApp3.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WpfApp3.Models.Stoc", "Stoc")
                        .WithMany()
                        .HasForeignKey("ProducatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Stoc");
                });

            modelBuilder.Entity("WpfApp3.Models.Stoc", b =>
                {
                    b.HasOne("WpfApp3.Models.Produs", "Produs")
                        .WithMany()
                        .HasForeignKey("ProdusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("WpfApp3.Models.Vanzare", b =>
                {
                    b.HasOne("WpfApp3.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("WpfApp3.Models.BonCasa", b =>
                {
                    b.Navigation("Detalii");
                });
#pragma warning restore 612, 618
        }
    }
}
